plugins {
    id "com.android.application"
}

def appBuildNumber = 6

android {
    namespace "ru.timptr.statuswidget"
    compileSdk 35

    defaultConfig {
        applicationId "ru.timptr.statuswidget"
        minSdk 29
        targetSdk 32
        versionCode appBuildNumber
        versionName "1.0.${appBuildNumber}"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation "com.getpebble:pebblekit:4.0.1"
}

androidComponents {
    onVariants(selector().withBuildType("debug")) { variant ->
        variant.outputs.forEach { output ->
            output.outputFileName.set("check-widget-debug-build-${appBuildNumber}.apk")
        }
    }
}
